-- Historical reference only.
--
-- The production schema lives in /migrations and is applied with
-- `npm run migrate`. Do not run this file against any environment; it is kept
-- so older deployment notes remain readable.
